### PR TITLE
Time walk scan. Merged with Mark.

### PR DESCRIPTION
**Pull request by cgottard**

### CODE REVIEW

**Comment by themperek** [comment]
What is fe65p2/scans/threshold_scan_t.py?

**Comment by cgottard** [comment]
It's the time walk scan.
Not a good name indeed...

_Message written on a small keyboard._

**Comment by themperek** [comment]
Then what is fe65p2/scans/timewalk_scan.py?

**Comment by cgottard** [comment]
You can erase timewalk_scan.py.
It was just the first attempt, probably was restored after my merging with mark.

**Comment by themperek** [comment]
You should remove this.

**Comment by themperek** [comment]
You removed wrong file as far as I cen see ?

**Comment by cgottard** [comment]
No, the right file is threshold_scan_t.py but let me rename it first and then I’ll make a decent pull request.

**Comment by themperek** [comment]
Should I marge this or not?

**Comment by themperek** [comment]
fe65p2/scans/threshold_scan.py and firmware/src/fe65p2_mio.v are wrong

**Comment by cgottard** [comment]
No, I closed it.
Merge the pull request I made about 1 hour ago.

Thanks.

**Pull request closed without merging**
